pipeline{
    agent any
    stages {
	stage('code checkout') {
            steps {
		git branch: 'main', crendentialsId: 'github-ssh-key', url: 'git@github.com:lavanyayadav72/jenkins_maven_pipeline.git'
            }
       }
    }
}
